FauxBonCoin/Controllers/AnnoncesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using FauxBonCoin.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace FauxBonCoin.Controllers
{
    public class AnnoncesController : Controller
    {
        public IActionResult Index(int? idCategory)
        {
            UserConnect(ViewBag);
            ViewBag.categories = Category.GetCategories();
            List<Annonce> liste = Annonce.LoadAnnonces(idCategory);
            return View(liste);
        }

        [Route("[Controller]/{id?}")]
        public IActionResult Detail(int? id)
        {
            UserConnect(ViewBag);
            return View();
        }
        [Route("[Controller]/Deposer")]
        public IActionResult DeposerAnnonce()
        {
            UserConnect(ViewBag);
            bool connected = Convert.ToBoolean(HttpContext.Session.GetString("logged"));
            if(connected)
            {
                Annonce a = new Annonce();
                ViewBag.ListeCategories = Category.GetCategories();
                return View("Depot",a);
            }
            else
            {
                return RedirectToRoute(new { controller = "Utilisateurs", action = "Login" });
            }
            
        }

        [Route("[Controller]/DeposerAnnoncePost")]
        [HttpPost]
        public async Task<IActionResult> DeposerAnnoncePost(string titre, string description, decimal? prix, int? categorie, List<IFormFile> images)
        {
            Annonce a = new Annonce() { Titre = titre, Description = description, Prix = (decimal)prix, IdCategory = (int)categorie };
            a.IdUser = Convert.ToInt32(HttpContext.Session.GetString("idUser"));
            List<string> errors = new List<string>();
            if(titre == null)
            {
                errors.Add("Merci d'indiquer un titre d'annonce");
            }
            if (description == null)
            {
                errors.Add("Merci d'indiquer une description d'annonce");
            }
            if (prix == null)
            {
                errors.Add("Merci d'indiquer un prix à l'annonce");
            }
            if (categorie == null)
            {
                errors.Add("Merci d'indiquer une catégorie d'annonce");
            }
            if(errors.Count > 0)
            {
                
                ViewBag.error = true;
                ViewBag.errors = errors;
                return View("Depot", a);
            }
            else
            {
                foreach(IFormFile f in images)
                {
                    if(f.FileName.Contains(".png") || f.FileName.Contains(".jpg"))
                    {
                       
                        var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images/annonces", a.IdUser.ToString() + "-" + f.FileName);
                        var stream = new FileStream(path, FileMode.Create);
                        await f.CopyToAsync(stream);
                        a.Images.Add(new ImageAnnonce { Url = "images/annonces/" + a.IdUser.ToString() + "-" + f.FileName });
                    }
                    
                }
                
                a.Add();
                return RedirectToAction("Index");
            }
        }

        [Route("Categorie")]
        public IActionResult ListeCategories()
        {
            UserConnect(ViewBag);
            List<Category> liste = Category.GetCategories();
            return View("ListeCategories",liste);
        }
        [Route("Categorie/Add")]
        public IActionResult AjouterCategorie()
        {
            UserConnect(ViewBag);
            return View("AddCategorie");
        }

        [Route("Categorie/Register")]
        [HttpPost]
        public IActionResult RegisterCategory(string titre)
        {
            Category c = new Category { Titre = titre };
            c.Add();
            return RedirectToAction("ListeCategories");
        }

        public IActionResult DeleteCategory(int id)
        {
            Category c = new Category { Id = id };
            c.Delete();
            return RedirectToAction("ListeCategories");
        }

        private void UserConnect(dynamic v)
        {
            bool? logged = Convert.ToBoolean(HttpContext.Session.GetString("logged"));
            if(logged == true)
            {
                v.Logged = logged;
                v.Nom = HttpContext.Session.GetString("nom");
                v.Prenom = HttpContext.Session.GetString("prenom");
            }
        }
    }
}

FauxBonCoin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FauxBonCoin</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">FauxBonCoin</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - FauxBonCoin</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

FauxBonCoin/Views/Shared/_LayoutBonCoin.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>_LayoutBonCoin</title>
    <link rel="stylesheet" href="~/css/CssBonCoin.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="row">
                    <div class="col-lg-2">
                        <a asp-area="" asp-controller="Annonces" asp-action="Index" class="navbar-brand"><img class="logo" src="~/images/logoBonCoin.png" /></a>
                    </div>
                    <div class="col-lg-3">
                        <a asp-controller="Annonces" asp-action="DeposerAnnonce">Deposer une annonce</a>
                    </div>
                    <div class="col-lg-2">
                        <a asp-area="" asp-controller="Annonces" asp-action="Index">offres</a>
                    </div>
                    @if (ViewBag.Logged == true)
                    {
                    <div class="col-lg-offset-2 col-lg-3">
                        <span class="UserInfo">@ViewBag.Nom @ViewBag.Prenom</span>
                        <a asp-controller="Utilisateurs" asp-action="LogOut"> Log out</a>
                    </div>
                    }
                    else
                    {
                        <div class="col-lg-offset-3 col-lg-2">
                            <a asp-area="" asp-controller="Utilisateurs" asp-action="Login">se connecter</a>
                        </div>
                        
                    }

                </div>
            </div>
        </nav>
    </header>
    <section class="container">
        @RenderBody()
    </section>
</body>
</html>