FauxBonCoin/Models/Utilisateur.cs
using FauxBonCoin.Tools;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FauxBonCoin.Models
{
    public class Utilisateur
    {
        private int id;
        private string nom;
        private string prenom;
        private string email;
        private string telephone;
        private string password;

        public int Id { get => id; set => id = value; }
        public string Nom { get => nom; set => nom = value; }
        public string Prenom { get => prenom; set => prenom = value; }
        public string Email { get => email; set => email = value; }
        public string Telephone { get => telephone; set => telephone = value; }
        public string Password { get => password; set => password = value; }

        public bool Exist()
        {
            return DataBase.Instance.LookUser(this);
        }

        public bool ExistWithPassword()
        {
            return DataBase.Instance.LookUser(Email, Password, this);
        }

        public void Add()
        {
            DataBase.Instance.AddUser(this);
        }

    }
}

FauxBonCoin/Controllers/UtilisateursController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FauxBonCoin.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace FauxBonCoin.Controllers
{
    public class UtilisateursController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [Route("[Controller]/Login")]
        public IActionResult Login()
        {
            Utilisateur u = new Utilisateur();
            return View(u);
        }

        [HttpPost]
        public IActionResult LoginPost(string email, string password)
        {
            Utilisateur u = new Utilisateur { Email = email, Password = password };
            List<string> errors = new List<string>();
            if(email == null)
            {
                errors.Add("Merci de saisir un email");
            }
            if(password == null)
            {
                errors.Add("Merci de saisir un mot de passe");
            }
            if (!u.ExistWithPassword())
            {
                errors.Add("Aucun utilisateur avec cette email et mot de passe");
            }
            if(errors.Count > 0)
            {
                ViewBag.errors = errors;
                return View("Login",u);
            }
            else
            {
                HttpContext.Session.SetString("logged", "true");
                HttpContext.Session.SetString("nom", u.Nom);
                HttpContext.Session.SetString("prenom", u.Prenom);
                HttpContext.Session.SetString("idUser", u.Id.ToString());
                return RedirectToRoute(new { controller = "Annonces", action = "Index" });
            }
        }

        [HttpPost]
        public IActionResult Register(string nom, string prenom, string email, string telephone, string password, string cPassword)
        {
            List<string> errors = new List<string>();
            Utilisateur u = new Utilisateur { Nom = nom, Prenom = prenom, Email = email, Telephone = telephone, Password = password };
            if(nom == null)
            {
                errors.Add("Merci de saisir un Nom");
            }
            if(prenom == null)
            {
                errors.Add("Merci de saisir un prénom");
            }
            if(email  == null)
            {
                errors.Add("Merci de saisir un email");
            }
            if(telephone == null)
            {
                errors.Add("Merci de saisir un numéro de téléphone");
            }
            if(password == null)
            {
                errors.Add("Merci de saisir un mot de passe");
            }
            if(password != cPassword)
            {
                errors.Add("Merci de saisir le même mot de passe");
            }
            if (u.Exist())
            {
                errors.Add("Cette adresse email est déjà utilisée");
            }
            ViewBag.errors = errors;
            if(errors.Count > 0)
            {
                
            }
            else
            {
                u.Add();
                ViewBag.Inscription = true;
                ViewBag.Message = "Inscription reussie merci de vous connecter";
            }
            return View("Login", u);
        }

        public IActionResult LogOut()
        {
            HttpContext.Session.Clear();
            return RedirectToRoute(new { controller = "Annonces", action = "Index" });
        }
    }
}

FauxBonCoin/Views/Utilisateurs/Login.cshtml
<div class="row">
    <div class="col-lg-12">
        @if ((ViewBag.errors != null))
        {
            if ((ViewBag.errors as List<string>).Count > 0)
            {
                <div class="row">
                    <div class="col-lg-12 alert alert-danger">
                        @foreach (string e in (ViewBag.errors as List<string>))
                        {
                            <div class="row">
                                <div class="col-lg-12">
                                    @e
                                </div>
                            </div>
                        }
                    </div>
                </div>
            }
        }
    </div>
</div>
<div class="row">
    <div class="col-lg-6">
        <div class="Inscription">
            <div class="row">
                <h2 class="col-lg-12">Inscription</h2>
            </div>
            
            @if (ViewBag.Inscription != null)
            {
                if (ViewBag.Inscription)
                {
                    <div class="row">
                        <div class="col-lg-12 alert alert-success">
                            @ViewBag.Message
                        </div>
                    </div>
                }
            }
            <form asp-controller="Utilisateurs" asp-action="Register" method="post">
                <div class="row">
                    <div class="col-lg-12">
                        <input type="text" class="form-control" value="@Model.Nom" name="nom" placeholder="Votre Nom" />
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <input type="text" class="form-control" value="@Model.Prenom" name="prenom" placeholder="Votre Prénom" />
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <input type="text" class="form-control" value="@Model.Email" name="email" placeholder="Votre Email" />
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <input type="text" class="form-control" value="@Model.Telephone" name="telephone" placeholder="Votre Téléphone" />
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <input type="password" class="form-control" value="@Model.Password" name="password" placeholder="Votre password" />
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <input type="password" class="form-control" name="cPassword" placeholder="Confirmation password" />
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <button class="form-control btn btn-default" type="submit">S'inscrire</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="col-lg-6">
        <div class="Login">
            <div class="row">
                <h2 class="col-lg-12">Se connecter</h2>
            </div>
            <form asp-controller="Utilisateurs" asp-action="LoginPost">
                <div class="row">
                    <div class="col-lg-12">
                        <input type="text" class="form-control" name="email" placeholder="Votre Email" />
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-12">
                        <input type="password" class="form-control" name="password" placeholder="Votre password" />
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <button class="form-control btn btn-default" type="submit">Se connecter</button>
                    </div>
                </div>
            </form>
            </div>
        </div>
    </div>